name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

jobs:
  try_release_please:
    uses: ./.github/workflows/release-reusable.yml
    with:
      runs_on: "ubuntu-latest"
      continue_on_error: true

  fallback_release_please:
    needs: [try_release_please]
    if: ${{ failure() }}
    uses: ./.github/workflows/release-reusable.yml
    with:
      runs_on: '[ "self-hosted", "linux" ]'
